info:
  component: Discovery Server

server:
  port: 8761
  ssl:
    key-store: classpath:cert.p12
    key-store-password: c9xZpx
    enabled: true
  http2.enable: true   


logstash:
 host: 127.0.0.1:5000

spring:
  rabbitmq:
    host: localhost
    port: 5672
  sleuth:
    sampler:
      percentage: 0.2 

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
  server.enableSelfPreservation: false
     

logging:
  level:
    root: WARN

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO



---
# Eureka instance when used on Docker
spring:
  profiles: docker
  
spring.rabbitmq.host: rabbitmq  

logstash:
 host: logstash:5000
  
