message: Hello world3

server:
  port: 0
  ssl:
    discovery-client-key-store: src/main/resources/cert.p12
    key-store: classpath:cert.p12
    key-store-password: c9xZpx
  http2.enable: true

info:
  component: Product Service

logstash:
 host: 127.0.0.1:5000

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/shop-db
    username: shop
    password: shop
    driverClassName: org.postgresql.Driver    
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop


logging:
  level:
    root: WARN

    # Get info on failed OAuth access token validations
    org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoTokenServices: INFO

    # Get info regarding connection to the cofig server and retries if required
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO

    # Set DEBUG level on Hystrix to get an error message when a fallback method is used.
    com.netflix.hystrix: DEBUG
    com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedArchaiusProperty: WARN
    de.maltorpro: INFO


---
# For deployment in Docker containers
spring:
  profiles: docker
  
spring.datasource.url: jdbc:postgresql://shop-db:5432/shop-db

server:
  port: 8080

spring.rabbitmq.host: rabbitmq

logstash:
 host: logstash:5000

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: https://discovery-server:8761/eureka/
