turbine.stream.port: 8989

server:
  ssl:
    key-store: classpath:cert.p12
    key-store-password: c9xZpx
  http2.enable: true

management:
  port: 8990

info:
  component: Turbine Server


logging:
  level:
    root: WARN
    com.netflix.discovery: 'OFF'

    # Get info regarding connection to the cofig server and retries if required
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG

    # org.springframework.integration: DEBUG

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO

spring.rabbitmq:
  host: localhost
  port: 5672

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:https://user:password@localhost:8761}/eureka/


---
# For deployment in Docker containers
spring:
  profiles: docker

spring.rabbitmq.host: rabbitmq

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: https://discovery-server:8761/eureka/

